# RT-Thread building script for component

from building import *
Import('rtconfig')

cwd = GetCurrentDir()
src = Glob('*.cpp') + Glob('*.c')

CPPPATH = [cwd]

if rtconfig.PLATFORM == 'armclang':
    src += Glob('arm_tpl/*.cpp') + Glob('arm_tpl/*.c')
    CPPPATH += [cwd + '/arm_tpl']

group = DefineGroup('CPlusPlus', src, depend = ['RT_USING_CPLUSPLUS'], CPPPATH = CPPPATH)

Return('group')
